name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18.0-beta2'

    - name: Build
      run: go build -v ./...

    - name: Test qrcode
      working-directory: .
      run: go test -v ./...
      continue-on-error: false

    - name: Test writer/standard
      working-directory: ./writer/standard
      run: go mod tidy && mkdir testdata && go test -v ./...
      continue-on-error: false

    - name: Test writer/terminal
      working-directory: ./writer/terminal
      run: go mod tidy && mkdir testdata && go test -v ./...
      continue-on-error: false
